title: Dispositivos Biomédicos Inteligentes
description: Innovación en IA y Sistemas Embebidos.
baseurl: "" # Déjalo vacío si el repo se llama 'usuario.github.io'
url: "https://cribnez.github.io"

# Ajustes de Jekyll
theme: minima
plugins:
  - jekyll-feed
