title: Dispositivos Biomédicos Inteligentes
description: Innovación en IA y Sistemas Embebidos.
baseurl: "/dbi-research-web"
url: "https://cribnez.github.io"

# Ajustes de Jekyll
theme: minima
plugins:
  - jekyll-feed

# --- NUEVA CONFIGURACIÓN DE COLECCIONES ---
# Esto le dice a Jekyll que cree las páginas de tus proyectos de forma automatizada
collections:
  proyectos:
    output: true
    permalink: /proyectos/:path/
  estadias:
    output: true
    permalink: /estadias/:path/
  noticias:
    output: true
