title: Dispositivos Biomédicos Inteligentes
description: Innovación en IA y Sistemas Embebidos.
baseurl: "/dbi-research-web"
url: "https://cribnez.github.io"

# Ajustes de Jekyll
theme: minima
plugins:
  - jekyll-feed
